language: python
matrix:
    include:
        - python: 2.7
          env:
              - TOX_ENV=images
        - python: 3.5
          env:
              - TOX_ENV=images
        - python: 2.7
          env:
              - TOX_ENV=integration
        - python: 3.6
          env:
              - TOX_ENV=integration
        - python: 2.7
          env:
              - TOX_ENV=selenium
        - python: 3.6
          env:
              - TOX_ENV=selenium
        - python: 3.6
          env:
              - TOX_ENV=lint
install:
  - pip install -U tox
before_script:
  - export APPLITOOLS_BATCH_ID=`uuidgen -t`
  - echo $APPLITOOLS_BATCH_ID
script:
  - tox -e $TOX_ENV
